if (!(Test-Path -Path C:\temp )) { New-Item -ItemType directory -Path C:\temp };secedit /export /cfg C:\temp\secpol.cfg;
Write-Output '====';
[System.Net.Dns]::GetHostName();
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'PasswordHistorySize =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'MaximumPasswordAge =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'MinimumPasswordAge =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'MinimumPasswordLength =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'PasswordComplexity =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'ClearTextPassword =';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'ForceLogoffWhenHourExpire =';Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows Nt\Currentversion' -Name 'CurrentBuild';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\SAM' -Name 'RelaxMinimumPasswordLengthLimits';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'NoConnectedUser';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'LimitBlankPasswordUse';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'SCENoApplyLegacyAuditPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'CrashOnAuditFail';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'AllocateDASD';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'RequireSignOrSeal';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'SealSecureChannel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'SignSecureChannel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'DisablePasswordChange';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'MaximumPasswordAge';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters' -Name 'RequireStrongKey';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'DisableCAD';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'DontDisplayLastUserName';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'InactivityTimeoutSecs';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'PasswordExpiryWarning';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'ScRemoveOption';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'RequireSecuritySignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'EnableSecuritySignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'EnablePlainTextPassword';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'AutoDisconnect';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'RequireSecuritySignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'EnableSecuritySignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'enableforcedlogoff';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'SMBServerNameHardeningLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'RestrictAnonymousSAM';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'RestrictAnonymous';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'DisableDomainCreds';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'EveryoneIncludesAnonymous';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters' -Name 'NullSessionPipes';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedExactPaths' -Name 'Machine';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedPaths' -Name 'Machine';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'RestrictNullSessAccess';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'restrictremotesam';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'NullSessionShares';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'ForceGuest';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'UseMachineId';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'AllowNullSessionFallback';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\pku2u' -Name 'AllowOnlineID';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters' -Name 'SupportedEncryptionTypes';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'NoLMHash';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'LMCompatibilityLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LDAP' -Name 'LDAPClientIntegrity';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'NTLMMinClientSec';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'NTLMMinServerSec';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Session Manager\Kernel' -Name 'ObCaseInsensitive';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Session Manager' -Name 'ProtectionMode';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'FilterAdministratorToken';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorAdmin';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorUser';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableInstallerDetection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableSecureUIAPaths';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableLUA';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'PromptOnSecureDesktop';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableVirtualization';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Browser' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\IISADMIN' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\irmon' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\SharedAccess' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LxssManager' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\FTPSVC' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\sshd' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\RpcLocator' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\RemoteAccess' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\simptcp' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\sacsvr' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\SSDPSRV' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\upnphost' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\WMSvc' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\WMPNetworkSvc' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\icssvc' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\W3SVC' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\XboxGipSvc' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\XblAuthManager' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\XblGameSave' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\XboxNetApiSvc' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'EnableFirewall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'DefaultInboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'DefaultOutboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile' -Name 'DisableNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging' -Name 'LogFilePath';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging' -Name 'LogFileSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging' -Name 'LogDroppedPackets';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile\Logging' -Name 'LogSuccessfulConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'EnableFirewall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'DefaultInboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'DefaultOutboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile' -Name 'DisableNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging' -Name 'LogFilePath';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging' -Name 'LogFileSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging' -Name 'LogDroppedPackets';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging' -Name 'LogSuccessfulConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'EnableFirewall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'DefaultInboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'DefaultOutboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'DisableNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'AllowLocalPolicyMerge';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile' -Name 'AllowLocalIPsecPolicyMerge';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging' -Name 'LogFilePath';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging' -Name 'LogFileSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging' -Name 'LogDroppedPackets';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging' -Name 'LogSuccessfulConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Personalization' -Name 'NoLockScreenCamera';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Personalization' -Name 'NoLockScreenSlideshow';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\InputPersonalization' -Name 'AllowInputPersonalization';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\GPExtensions\{D76B9641-3288-4f75-942D-087DE603E3EA}' -Name 'DllName';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft Services\AdmPwd' -Name 'PwdExpirationProtectionEnabled';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft Services\AdmPwd' -Name 'AdmPwdEnabled';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft Services\AdmPwd' -Name 'PasswordComplexity';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft Services\AdmPwd' -Name 'PasswordLength';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft Services\AdmPwd' -Name 'PasswordAgeDays';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'LocalAccountTokenFilterPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters' -Name 'SMB1';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel' -Name 'DisableExceptionChainValidation';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint' -Name 'RestrictDriverInstallationToAdministrators';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Netbt\Parameters' -Name 'NodeType';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest' -Name 'UseLogonCredential';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'AutoAdminLogon';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Tcpip6\Parameters' -Name 'DisableIPSourceRouting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters' -Name 'DisableIPSourceRouting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters' -Name 'EnableICMPRedirect';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\NetBT\Parameters' -Name 'nonamereleaseondemand';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager' -Name 'SafeDllSearchMode';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'ScreenSaverGracePeriod';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Eventlog\Security' -Name 'WarningLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient' -Name 'DoHPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient' -Name 'EnableMulticast';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'AllowInsecureGuestAuth';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Network Connections' -Name 'NC_AllowNetBridge_NLA';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Network Connections' -Name 'NC_ShowSharedAccessUI';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Network Connections' -Name 'NC_StdDomainUserSetLocation';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths' -Name '\\*\NETLOGON';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths' -Name '\\*\SYSVOL';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WcmSvc\GroupPolicy' -Name 'fMinimizeConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WcmSvc\GroupPolicy' -Name 'fBlockNonDomain';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\config' -Name 'AutoConnectAllowedOEM';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers' -Name 'RegisterSpoolerRemoteRpcEndPoint';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint' -Name 'NoWarningNoElevationOnInstall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint' -Name 'UpdatePromptSettings';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System\Audit' -Name 'ProcessCreationIncludeCmdLine_Enabled';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters' -Name 'AllowEncryptionOracle';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation' -Name 'AllowProtectedCreds';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Device Metadata' -Name 'PreventDeviceMetadataFromNetwork';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Policies\EarlyLaunch' -Name 'DriverLoadPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Group Policy\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}' -Name 'NoBackgroundPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Group Policy\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}' -Name 'NoGPOListChanges';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\System' -Name 'EnableCdp';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers' -Name 'DisableWebPnPDownload';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoWebServices';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\System' -Name 'BlockUserFromShowingAccountDetailsOnSignin';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'DontDisplayNetworkSelectionUI';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'DontEnumerateConnectedUsers';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'EnumerateLocalUsers';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'DisableLockScreenAppNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'BlockDomainPicturePassword';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'AllowDomainPINLogon';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\f15576e8-98b7-4186-b944-eafa664402d9' -Name 'DCSettingIndex';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\f15576e8-98b7-4186-b944-eafa664402d9' -Name 'ACSettingIndex';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51' -Name 'DCSettingIndex';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51' -Name 'ACSettingIndex';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\policies\Microsoft\Windows NT\Terminal Services' -Name 'fAllowUnsolicited';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\policies\Microsoft\Windows NT\Terminal Services' -Name 'fAllowToGetHelp';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Rpc' -Name 'EnableAuthEpResolution';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Rpc' -Name 'RestrictRemoteClients';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Appx' -Name 'BlockNonAdminUserInstall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\AppPrivacy' -Name 'LetAppsActivateWithVoiceAboveLock';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'MSAOptional';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'NoAutoplayfornonVolume';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoAutorun';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoDriveTypeAutoRun';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures' -Name 'EnhancedAntiSpoofing';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent' -Name 'DisableConsumerAccountStateContent';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Cloudcontent' -Name 'DisableWindowsConsumerFeatures';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Connect' -Name 'RequirePinForPairing';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Credui' -Name 'DisablePasswordReveal';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Credui' -Name 'EnumerateAdministrators';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'NoLocalPasswordResetQuestions';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DataCollection' -Name 'AllowTelemetry';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DataCollection' -Name 'DisableOneSettingsDownloads';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Datacollection' -Name 'DoNotShowFeedbackNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Datacollection' -Name 'EnableOneSettingsAuditing';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Datacollection' -Name 'LimitDiagnosticLogCollection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Datacollection' -Name 'LimitDumpCollection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Previewbuilds' -Name 'AllowBuildPreview';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DeliveryOptimization' -Name 'DODownloadMode';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\Application' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\Security' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\Setup' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Eventlog\Setup' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\System' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\System' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'NoDataExecutionPrevention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'NoHeapTerminationOnCorruption';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'PreXPSP2ShellProtocolBehavior';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\HomeGroup' -Name 'DisableHomeGroup';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftAccount' -Name 'DisableUserAuth';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet' -Name 'LocalSettingOverrideSpynetReporting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR' -Name 'ExploitGuard_ASR_Rules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '26190899-1602-49e8-8b27-eb1d0a1ce869';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '3b576869-a4ec-4529-8536-b80a7769e899';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '5beb7efe-fd9a-4556-801d-275e5ffc04cc';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '7674ba52-37eb-4a4f-a9a1-f0f9a1619a2c';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '92e97fa1-2edf-4476-bdd6-9dd0b4dddc7b';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name '9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name 'b2b3f03d-6a65-4f7b-a9c7-1c7ef74a9ba4';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name 'be9ba2d9-53ea-4cdc-84e5-9b1eeee46550';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name 'd3e037e1-3eb8-44c8-a917-57927947596d';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules' -Name 'd4f940ab-401b-4efc-aadc-ad5f3c50688a';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection' -Name 'EnableNetworkProtection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableIOAVProtection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableRealtimeMonitoring';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableBehaviorMonitoring';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection' -Name 'DisableScriptScanning';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Scan' -Name 'DisableRemovableDriveScanning';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Scan' -Name 'DisableEmailScanning';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender' -Name 'PUAProtection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender' -Name 'DisableAntiSpyware';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\OneDrive' -Name 'DisableFileSyncNGSC';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name 'DisablePasswordSaving';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name 'fDisableCdm';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name 'fPromptForPassword';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'fEncryptRPCTraffic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name 'SecurityLayer';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name 'UserAuthentication';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name 'MinEncryptionLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name 'DeleteTempDirsOnExit';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Feeds' -Name 'DisableEnclosureDownload';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search' -Name 'AllowCortana';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search' -Name 'AllowCortanaAboveLock';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search' -Name 'AllowIndexingEncryptedStoresOrItems';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search' -Name 'AllowSearchToUseLocation';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore' -Name 'RequirePrivateStoreOnly';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore' -Name 'AutoDownload';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore' -Name 'DisableOSUpgrade';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Dsh' -Name 'AllowNewsAndInterests';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'EnableSmartScreen';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\System' -Name 'ShellSmartScreenLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter' -Name 'EnabledV9';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter' -Name 'PreventOverride';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\GameDVR' -Name 'AllowGameDVR';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace' -Name 'AllowWindowsInkWorkspace';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Installer' -Name 'EnableUserControl';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Installer' -Name 'AlwaysInstallElevated';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'DisableAutomaticRestartSignOn';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Powershell\Scriptblocklogging' -Name 'EnableScriptBlockLogging';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription' -Name 'EnableTranscripting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowBasic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowUnencryptedTraffic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowDigest';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Service' -Name 'AllowBasic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service' -Name 'AllowUnencryptedTraffic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Winrm\Service' -Name 'DisableRunAs';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Sandbox' -Name 'AllowClipboardRedirection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Sandbox' -Name 'AllowNetworking';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\App and Browser protection' -Name 'DisallowExploitProtectionOverride';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Windowsupdate\Au' -Name 'NoAutoRebootWithLoggedOnUsers';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Windowsupdate\Au' -Name 'NoAutoUpdate';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Windowsupdate\Au' -Name 'ScheduledInstallDay';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate' -Name 'SetDisablePauseUXAccess';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate' -Name 'ManagePreviewBuildsPolicyValue';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate' -Name 'DeferFeatureUpdates';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Windowsupdate' -Name 'DeferFeatureUpdatesPeriodInDays';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate' -Name 'DeferQualityUpdates';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate' -Name 'DeferQualityUpdatesPeriodInDays';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop' -Name 'ScreenSaveActive';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop' -Name 'ScreenSaverIsSecure';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop' -Name 'ScreenSaveTimeOut';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\CurrentVersion\PushNotifications' -Name 'NoToastApplicationNotificationOnLockScreen';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments' -Name 'SaveZoneInformation';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments' -Name 'ScanWithAntiVirus';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoInplaceSharing';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\CloudContent' -Name 'ConfigureWindowsSpotlight';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\CloudContent' -Name 'DisableThirdPartySuggestions';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\CloudContent' -Name 'DisableSpotlightCollectionOnDesktop';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\Installer' -Name 'AlwaysInstallElevated';Write-Output '====';
net accounts | select-string -pattern 'Lockout duration';
Write-Output '====';
net accounts | select-string -pattern 'Lockout threshold';
Write-Output '====';
net accounts | select-string -pattern 'Lockout observation window';Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeTrustedCredManAccessPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeNetworkLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeTcbPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeIncreaseQuotaPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeInteractiveLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeRemoteInteractiveLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeBackupPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeSystemTimePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeTimeZonePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreatePagefilePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreateTokenPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreateGlobalPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreatePermanentPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreateSymbolicLinkPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDebugPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyNetworkLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyBatchLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyServiceLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyInteractiveLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyRemoteInteractiveLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeEnableDelegationPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeRemoteShutdownPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeAuditPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeImpersonatePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeIncreaseBasePriorityPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeLoadDriverPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeLockMemoryPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeSecurityPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeReLabelPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeSystemEnvironmentPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeManageVolumePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeProfileSingleProcessPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeSystemProfilePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeAssignPrimaryTokenPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeRestorePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeShutdownPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeTakeOwnershipPrivilege';Write-Output '====';
net user administrator | select-string -pattern 'Account active';
Write-Output '====';
net user guest | select-string -pattern 'Account active';
Write-Output '===='
net user administrator | select-string -pattern 'User name';
Write-Output '====';
net user guest | select-string -pattern 'User name';Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'LegalNoticeText';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System' -Name 'LegalNoticeCaption';Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'LSAAnonymousNameLookup =';Write-Output '====';
auditpol /get /subcategory:'Credential Validation' | select-string -pattern 'Credential Validation';
Write-Output '====';
auditpol /get /subcategory:'Application Group Management' | select-string -pattern 'Application Group Management';
Write-Output '====';
auditpol /get /subcategory:'Security Group Management' | select-string -pattern 'Security Group Management';
Write-Output '====';
auditpol /get /subcategory:'User Account Management' | select-string -pattern 'User Account Management';
Write-Output '====';
auditpol /get /subcategory:'Plug and Play Events' | select-string -pattern 'Plug and Play Events';
Write-Output '====';
auditpol /get /subcategory:'Process Creation' | select-string -pattern 'Process Creation';
Write-Output '====';
auditpol /get /subcategory:'Account Lockout' | select-string -pattern 'Account Lockout';
Write-Output '====';
auditpol /get /subcategory:'Group Membership' | select-string -pattern 'Group Membership';
Write-Output '====';
auditpol /get /subcategory:'Logoff' | select-string -pattern 'Logoff';
Write-Output '====';
auditpol /get /subcategory:'Logon' | select-string -pattern 'Logon';
Write-Output '====';
auditpol /get /subcategory:'Other Logon/Logoff Events' | select-string -pattern 'Other Logon/Logoff Events';
Write-Output '====';
auditpol /get /subcategory:'Special Logon' | select-string -pattern 'Special Logon';
Write-Output '====';
auditpol /get /subcategory:'Detailed File Share' | select-string -pattern 'Detailed File Share';
Write-Output '====';
auditpol /get /subcategory:'File Share' | select-string -pattern 'File Share';
Write-Output '====';
auditpol /get /subcategory:'Other Object Access Events' | select-string -pattern 'Other Object Access Events';
Write-Output '====';
auditpol /get /subcategory:'Removable Storage' | select-string -pattern 'Removable Storage';
Write-Output '====';
auditpol /get /subcategory:'Audit Policy Change' | select-string -pattern 'Audit Policy Change';
Write-Output '====';
auditpol /get /subcategory:'Authentication Policy Change' | select-string -pattern 'Authentication Policy Change';
Write-Output '====';
auditpol /get /subcategory:'Authorization Policy Change' | select-string -pattern 'Authorization Policy Change';
Write-Output '====';
auditpol /get /subcategory:'MPSSVC Rule-Level Policy Change' | select-string -pattern 'MPSSVC Rule-Level Policy Change';
Write-Output '====';
auditpol /get /subcategory:'Other Policy Change Events' | select-string -pattern 'Other Policy Change Events';
Write-Output '====';
auditpol /get /subcategory:'Sensitive Privilege Use' | select-string -pattern 'Sensitive Privilege Use';
Write-Output '====';
auditpol /get /subcategory:'IPsec Driver' | select-string -pattern 'IPsec Driver';
Write-Output '====';
auditpol /get /subcategory:'Other System Events' | select-string -pattern 'Other System Events';
Write-Output '====';
auditpol /get /subcategory:'Security State Change' | select-string -pattern 'Security State Change';
Write-Output '====';
auditpol /get /subcategory:'Security System Extension' | select-string -pattern 'Security System Extension';
Write-Output '====';
auditpol /get /subcategory:'System Integrity' | select-string -pattern 'System Integrity';Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\sacsvr' -Name 'nan';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'DisableBkGndGroupPolicy';;